######################## default configuration ####################
baseURL = "https://www.4koro.page/"
languageCode = "en-us"
title = "手作り/作りたての揚げ物とお弁当のお店 - 4丁目のコロッケ屋さん"
theme="restaurant-hugo"
summaryLength = "7"
paginate = 4

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/slick.css"
  [[params.plugins.css]]
  URL = "css/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "css/animate.min.css"
  [[params.plugins.css]]
  URL = "css/venobox.css"
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/responsive.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/slick.min.js"
  [[params.plugins.js]]
  URL = "js/wow.min.js"
  [[params.plugins.js]]
  URL = "js/venobox.min.js"
  [[params.plugins.js]]
  URL = "js/main.js"

############################## navigation ###############################
[menu]

	[[menu.main]]
  name = "ホーム"
  URL = "hero-area"
  weight = 1

  [[menu.main]]
  name = "お店について"
  URL = "about-us"
  weight = 2

#  [[menu.main]]
#  name = "Blog"
#  URL = "blog"
#  weight = 3

  [[menu.main]]
  name = "メニュー"
  URL = "price"
  weight = 3

#  [[menu.main]]
#  name = "News"
#  URL = "subscribe"
#  weight = 5

  [[menu.main]]
  name = "営業時間・連絡先"
  URL = "footer"
  weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "4丁目のコロッケ屋さん"
description = "4丁目のコロッケ屋さんでは、お惣菜やお弁当は注文いただいてから作るため、作りたての美味しさをお届けできます。創業1964年、昔ながらの味を守りながら、地域に密着したおいしいお惣菜・お弁当をどうぞお召し上がりください。"
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright 2020 - 4丁目のコロッケ屋さん All Rights Reserved. Design and Developed By Themefisher.com"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "営業時間"
# blogTitle = "LATEST <span>BLOG POSTS</span>"
# galleryTitle = "PHOTO <span>STREAM</span>"
# socialTitle = "Follow <span>US</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="営業時間"
icon = "fa fa-briefcase"
content = "10:00 ~ 19:00 （売り切れ次第終了）"

[[params.footer.contactItem]]
title="定休日"
icon = "fa fa-bell-slash"
content = "毎週月曜日、毎月第3火曜日"

# [[params.footer.contactItem]]
# title="電話番号"
# icon = "fa fa-phone"
# content = "0285-45-0607"

# [[params.footer.contactItem]]
# title="住所"
# icon = "fa fa-map-marker"
# content = "栃木県小山市大字間々田１６５１−６"

#[[params.footer.contactItem]]
# title="E mail"
# icon = "fa fa-envelope"
# content = "rest@gmail.com - rest@mail.ru"

######################### footer gallery
# [[params.footer.gallery]]
# image = "images/slider/slider-img-1.jpg"
#
# [[params.footer.gallery]]
# image = "images/slider/slider-img-2.jpg"
#
# [[params.footer.gallery]]
# image = "images/slider/slider-img-3.jpg"
#
# [[params.footer.gallery]]
# image = "images/slider/slider-img-4.jpg"
#
# [[params.footer.gallery]]
# image = "images/slider/slider-img-1.jpg"
#
# [[params.footer.gallery]]
# image = "images/slider/slider-img-2.jpg"

######################## Social Icon
# [[params.footer.socialLink]]
# icon = "facebook"
# link = "https://fb.com/themefisher"
#
# [[params.footer.socialLink]]
# icon = "twitter"
# link = "https://fb.com/themefisher"
#
# [[params.footer.socialLink]]
# icon = "dribbble"
# link = "https://fb.com/themefisher"
#
# [[params.footer.socialLink]]
# icon = "instagram"
# link = "https://fb.com/themefisher"
