[build]
command = "python scripts/build.py"
publish = "dist"

[[headers]]
for = "/menu.pdf"
  [headers.values]
  Content-Type = "application/pdf"
  Content-Disposition = "inline"
  Cache-Control = "public, max-age=0, must-revalidate"
